# Generated by Django 4.0.5 on 2022-08-24 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_blood_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('custom_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('patient_location', models.CharField(max_length=20)),
            ],
        ),
    ]
